---
header_logo_url:
header_logo_text: My project
header_links:
  - label: Search
    link: /

  - label: Distribution
    link: /distribution

  - label: References
    link: /references

  - label: Author
    link: /author

  - label: Common names
    link: /common_names
